name: Github Actions Test
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          script_stop: true
          script: |
            pwd
            ls -l
            touch secret.txt
            echo ${{ secrets.SSH_HOST }} >> secret.txt
